### ISSUE TITLE
I need some help in implementing bass.net

### ISSUE THREAD

**Issue by botiapa** [BinkanSalaryman/Discord-Audio-Stream-Bot#1]
Hi, I tried your bot and it worked perfectly. Now i want to implement bass.net to my project. I installed it already. I copied some of your code, but I can't get it working, could you send me some basic code that copies the data from the virtual audio cable to the discord speakstream? I noticed that you're using voicesets, But my bot is only connected to one guild, and channel, so if I understand it correctly I don't need to use voicesets.

Thanks for helping it's my first time using bass.net.

**Comment by BinkanSalaryman** [comment]
https://hastebin.com/jesoyoruso.cs - don't forget to compile with /unsafe, providing voice libraries and playing music to VAC in the background after filling the required fields.

**Comment by botiapa** [comment]
I tried your answer but it's not working. It connects, but it doesn't send any music. The strange things in  that your bot works but this doesn't. I removed the "shutdown" part from the code maybe that's the problem?

**Comment by BinkanSalaryman** [comment]
The shutdown part was more an example of how to stop the whole service. It triggers after 15 seconds and you should have heard some music if you have music running in the background with output device set to the VAC input...

**Comment by botiapa** [comment]
I'm running .net 4.6.1 is that okay?

**Comment by BinkanSalaryman** [comment]
Should be fine, although I'm using 4.5.2 for whatever reason.

**Comment by botiapa** [comment]
I created a whole new project and it's still now working.

**Comment by botiapa** [comment]
Can you give it a look if I send it to you?

**Comment by BinkanSalaryman** [comment]
Yea, but you know you can add me in Discord? I wrote my username in the readme.md.
