### ISSUE TITLE
Connecting and talking, but no sound.

### ISSUE THREAD

**Issue by dxwarlock** [BinkanSalaryman/Discord-Audio-Stream-Bot#10]
I have tried VB cable, and even VoiceMeterBanana. I can see the virtual mic levels working, but bot is silent.
Even using live physical mic, there is no output from the bot. It is lit up like its talking. Just no sound period.

**Comment by BinkanSalaryman** [comment]
Hi there, this is probably an issue with discord or discord.net (the discord api library in use) itself. I have experienced similar issues myself and am not sure why they happen. I assume nothing of interest is displayed in the console from the details given. I'm afraid I can't help it; the last time I tried the bot myself it seemed to work but it also silced my headphones - it might have been a driver issue OR discord doesn't being connected twice with same IP/computer with user & bot accounts.

**Comment by dxwarlock** [comment]
Yes sadly nothing at all in the console other than the usual expected output as if it was working.

I think its machine/listed sound sources/system specific related. I cant narrow it down.
On my personal machine I can get it to relay fine. On my laptop no luck. And on a VM (what I was going to run it in) no luck also.
All 3 are trying to use VB AudioCable as the input/output.

**Comment by OwendB1** [comment]
The bot has been working fine on my local pc, but it seems like the audio isn't being transmitted and after a reconnect to a new channel the bot also stops "talking". Might be some usefull info.
