### ISSUE TITLE
Any other Alternatives?

### ISSUE THREAD

**Issue by flleeppyy** [BinkanSalaryman/Discord-Audio-Stream-Bot#12]
I've been messing with this and It just doesn't work. I don't feel like going through the painful process of creating my own bot script to share desktop audio.

**Comment by MrDannyPicard** [comment]
> 
> 
> I've been messing with this and It just doesn't work. I don't feel like going through the painful process of creating my own bot script to share desktop audio.

Just got it working, want some help?

**Comment by Cybont** [comment]
@MrDannyPicard How did you get the bot to detect the virtual cable?

**Comment by MrDannyPicard** [comment]
In the config.json file, be sure to fully write the name of your audio source

like:
```
"voice": {
    "speak": {
      "enabled": true,
      "recordingDevice": "**SPOTIFY OUT (VB-Audio Virtual Cable)**",
      "audioType": "Mixed",
      "bitRate": 125304,
      "bufferMillis": 750
```

At the recordingDevice line.

The console window will help you with this if you didn't put the right thing anyway.

**Comment by BinkanSalaryman** [comment]
@flleeppyy @MrDannyPicard a new version (written in java) is up, hope that works for you well enough for now. (There are few bugs I can't quite get rid off yet...)
