### ISSUE TITLE
Increasing the Audio Quality?

### ISSUE THREAD

**Issue by MrDannyPicard** [BinkanSalaryman/Discord-Audio-Stream-Bot#13]
I know that discord as it limit in term of audio quality but i was wondering if i can up the bitrate of the bot itself.

Now in the config file i see a line named bitrate with a value of 98304, but i can;t seem to find what that bitrate refer to.

**Comment by BinkanSalaryman** [comment]
Hi, the config value "speakBitRate" is passed to [IAudioClient.CreatePCMStream](https://discord.foxbot.me/docs/api/Discord.Audio.IAudioClient.html?q=bitrate). As it has no decription in the docs, I can't say for sure what it does unless I take a look at the implementation. What I assumed when [coding it](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/blob/master/src/DASB.ConsoleApp/Config.cs) is this:
```
/// <summary>
/// network audio stream bit rate for the bot when speaking, default is 96 KiBit
/// special values: null to use channel's bit rate
/// </summary>
public int? speakBitRate = 96 * 1024;
```
