### ISSUE TITLE
"Spoken" audio is distorted, e.g. after re-joining channel

### ISSUE THREAD

**Issue by BinkanSalaryman** [BinkanSalaryman/Discord-Audio-Stream-Bot#17]
On some occasions bot users' spoken audio turns into a distorted version of itself. Only workaround so far is by issuing the commands "leave", then "join".

Occasions:
* Initially (not sure in which order(s) actions are required to reproduce this issue)
* After disconnecting from voice, then joining back
* After joining another guilds' voice instance, then joining back

**Comment by kissklas** [comment]
Just had this as well, or at least I think it's the same. With music playing it turned into a "jumble" of sound. Is it maybe feeding both the previous audio stream and initiating another one on top? It sound sort of like two instances of the same audio fighting each other. 

Safest bet for now at least is just restarting the bot after a disconnect.

**Comment by BinkanSalaryman** [comment]
Looks like that was a jda-related problem and the recent update fixed it.
