### ISSUE TITLE
Error parsing NaN value. Path 'general.botToken', line 3, position 17.

### ISSUE THREAD

**Issue by ProcrastinatorSal** [BinkanSalaryman/Discord-Audio-Stream-Bot#2]
Getting the following error when submitting newly made bot token:
https://i.imgur.com/1Az1kDF.png

It's erroring right at the token.

My json is as follows:
{
  "general": {
    "botToken": NDEyNDgzNTg0NTAzMzE2NDgw.DWK6yQ.Exu0oy23ETk.................
  },
  "voice": {
    "speak": {
      "enabled": true,
      "recordingDevice": null,
      "audioType": "Mixed",
      "bitRate": 98304,
      "bufferMillis": 1000
    },
    "listen": {
      "enabled": false,
      "playbackDevice": null
    }
  },
  "text": {
    "commands": {
      "botAgent": "tomoko",
      "permissions": {
        "defaultPermissions": "join() !leave() commands(path) !assign(user_or_role,permissions) ping(host)",
        "userPermissions": {},
        "rolePermissions": {}
      }
    }
  }
}

**Comment by BinkanSalaryman** [comment]
1. Don't post your bot token. It's like the password to log in with the bot.
2. Put it between ""
