### ISSUE TITLE
Start "speaking" / "listening" on RTC connect

### ISSUE THREAD

**Issue by BinkanSalaryman** [BinkanSalaryman/Discord-Audio-Stream-Bot#21]
Right now, audio streams are started right away after issuing "join" command. Better time to start streaming would be after RTC has actually connected. This would remove the initial warning message of falsely recognized lagging-behind / out-of-sync.

**Comment by MrDannyPicard** [comment]
I seem to have encounter an issue like that, such as Spotify sounding robotic and slowed-down.
To be fair i haven't tested this for more than 10 min but that issue wasn't there before.

Also, the run win64.bat doesn't seem to work for me (Using Window 10 64x here)

Altogether, This version seem much simpler to use and understand. 
Don't take any of this as a complain, i appreciate your work and thanks you for it.

**Comment by BinkanSalaryman** [comment]
@MrDannyPicard You refer to #17 , this ticket has nothing to do that bug I sadly can't seem to fix.

How did you get it to work if run win64.bat didn't work?
For me, run win32.bat does nothing, and run win64.bat successfully launches the program (using Windows 10 Pro x64).

**Comment by MrDannyPicard** [comment]
I use the win32.bat, this one work  for me.

**Comment by BinkanSalaryman** [comment]
Looks like that was a jda-related problem and the recent update fixed it.
