### ISSUE TITLE
Add support for stereo transmission!

### ISSUE THREAD

**Issue by NiklavsD** [BinkanSalaryman/Discord-Audio-Stream-Bot#28]
Discord supports only single channel transmission, but I've heard there is way around this with discord bots, so I tried with this one, but still didn't work. It was just mono.
I noticed, that "Go live" streaming supports stereo transmission. So that worked, when I tried streaming app and than the app would playback my voice in stereo. Bummer, that others have to join stream, in order to hear that ASMR xD.
If you can find way to implement stereo, that would be so great!!!

**Comment by BinkanSalaryman** [comment]
The audio is already sent as stereo to discord and works as expected, I've checked it with a left/right speaker test.

**Comment by NiklavsD** [comment]
╲⎝⧹ Niklavs ⧸⎠╱#3115
Can you than help me and tell, what exactly I'm doing wrong?
