### ISSUE TITLE
Unknown OpCode (8)

### ISSUE THREAD

**Issue by OpenPollSal** [BinkanSalaryman/Discord-Audio-Stream-Bot#3]
Getting this error every time I try to connect the bot to my guild
![image](https://user-images.githubusercontent.com/37787393/39334640-6f92c97e-497d-11e8-91bd-3ae744e86e0e.png)

**Comment by BinkanSalaryman** [comment]
It's not an error, only a warning from Discord.NET library. You can safely ignore it.
