### ISSUE TITLE
Bot no longer working (Discord update?)

### ISSUE THREAD

**Issue by kissklas** [BinkanSalaryman/Discord-Audio-Stream-Bot#30]
The bot currently stops at "Loading subsystems". The log shows:
[AWT-EventQueue-0] INFO DiscordAudioStreamBot - Logging in...

The bot is connected to the server, but is unresponsive to commands,

**Comment by nahupyrope** [comment]
Yeah, thought it was an issue on my end, bot for me shows
01:38:24.141 [main] INFO MainFrame - Hello World!
01:38:29.395 [AWT-EventQueue-0] INFO DiscordAudioStreamBot - Logging in...
01:46:20.687 [AWT-EventQueue-0] INFO DiscordAudioStreamBot - Logged off
01:46:20.697 [DASB Shutdown Hook] INFO MainFrame - Goodbye!

**Comment by post-m** [comment]
This appears to be related to discord's recent gateway update described here: https://support-dev.discord.com/hc/en-us/articles/360056426994-Gateway-Update-FAQ

I managed to get the bot working again by going to the discord bot settings and toggling 'PRESENCE INTENT' under 'Privileged Gateway Intents' on.

**Comment by kissklas** [comment]
Nice find! Cheers!

**Comment by FoxyLight** [comment]
> This appears to be related to discord's recent gateway update described here: https://support-dev.discord.com/hc/en-us/articles/360056426994-Gateway-Update-FAQ
> 
> I managed to get the bot working again by going to the discord bot settings and toggling 'PRESENCE INTENT' under 'Privileged Gateway Intents' on.

Awesome! Thanks for the find.

**Comment by BinkanSalaryman** [comment]
Thanks for the link and workaround @post-m 
I got a working solution locally and will close the ticket when I'm done with polishing a little bit here and there.
