### ISSUE TITLE
Bot can't connect to Discord

### ISSUE THREAD

**Issue by Ch3ryl** [BinkanSalaryman/Discord-Audio-Stream-Bot#35]
In the Home tab when I click the big 'ol button it signs in then immediately signs off. I do have "Server Members Intent" enabled.

**Comment by BinkanSalaryman** [comment]
Is there any hint in the log file?

**Comment by 8bit-coder** [comment]
01:04:59.993 [AWT-EventQueue-0] INFO DiscordAudioStreamBot - Logging in...
01:05:00.593 [JDA MainWS-WriteThread] INFO DiscordAudioStreamBot - Logged off

**Comment by Ch3ryl** [comment]
Is that in the app text file?

**Comment by BinkanSalaryman** [comment]
> Is that in the app text file?
Yes

**Comment by Arsh150** [comment]
not sure if this is the same issue Ch3ryl is having but once i click the big ol' button it goes from connecting websocket to awaiting login confirmation back to shut down

heres what the log says:
08:48:00.825 [AWT-EventQueue-0] INFO DiscordAudioStreamBot - Logging in...
08:48:02.298 [JDA MainWS-WriteThread] INFO DiscordAudioStreamBot - Logged off
