### ISSUE TITLE
I cant even open it (Sorry, i'm n00b)

### ISSUE THREAD

**Issue by Saikedelics** [BinkanSalaryman/Discord-Audio-Stream-Bot#39]
I'm from Brazil, and have no knowledge of code, so i'm sorry if i'm asking help for such basic stuff, but it says "Run win64.bat" but i canmt find this file anywhere, i really dont know how to do it, if anyone can help me i would be very glad!

**Comment by BinkanSalaryman** [comment]
The batch files are included in the download from README.md, please check that you did download the runnable, compiled program not just the source code.
