### ISSUE TITLE
Can I use a part of this code in my MIT licensed software?

### ISSUE THREAD

**Issue by noonworks** [BinkanSalaryman/Discord-Audio-Stream-Bot#4]
I found your product on [Discord.Net issue: Voice Is Not Working #798](https://github.com/RogueException/Discord.Net/issues/798).
I wrote my software with referring to your code, and it works well. Thank you!

Then I'm going to distribute my software with MIT license, but it includes a part of your code. Can I do so?

**Comment by BinkanSalaryman** [comment]
MIT license sounds ok, you may use my code.

**Comment by noonworks** [comment]
Thank you so much! 😄 😄 😄
