### ISSUE TITLE
follow-voice: bot does not send sound after switching channel

### ISSUE THREAD

**Issue by BenoitLafont** [BinkanSalaryman/Discord-Audio-Stream-Bot#40]
Hello, 

Thanks for the new feature. I just try it out and when my bot switch from chanel with me it will stop from sending audio. I need to mute/unmute it in the bot software.

I use the bot to stream audio using the VB audio virtual as a mic.

I'm on windows 10 64x.

here's my log.

[app.log](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/files/6238749/app.log)

**Comment by BinkanSalaryman** [comment]
Uhm... yea there is something wrong. I'll look into it later

**Comment by BinkanSalaryman** [comment]
I apologize for the bug, that was a kinda stupid one... :')
It's gone now
