### ISSUE TITLE
Stuck at "gradle build" on Mac

### ISSUE THREAD

**Issue by SirSoundfont** [BinkanSalaryman/Discord-Audio-Stream-Bot#42]
I'm following the provided instructions step by step. Running "gradle build" always results in an error, as well as any gradle commands like "test" or "tasks" or even "help". It says "Executing gradle builds as part of an undefined build is not supported". Either there are missing command line steps I need to take after "brew install gradle", or it might be because I don't have the Java SDK installed? Apparently JDK is a requirement for gradle but your provided instructions don't mention it at all.

**Comment by BinkanSalaryman** [comment]
[This guy](https://github.com/spkane) sent in the instructions for Mac; can you please ask him about it? I don't own a mac and thus can't check what to do to make the bot program work. Originally I thought a little shell script would be all it takes... :/

**Comment by SirSoundfont** [comment]
I don't know how I would be able to contact him. I found his twitter, but I'm unable to DM him, and I can't @ him because my account is private lol

**Comment by BinkanSalaryman** [comment]
@spkane Could you please confirm that MacOS instructions are correct and complete?

**Comment by spkane** [comment]
@BinkanSalaryman I can likely retest this at some point, but just Googling the error suggests that this might be related to changes in Gradle 7. https://discuss.gradle.org/t/executing-gradle-tasks-as-part-of-an-undefined-build-has-been-deprecated-this-will-fail-with-an-error-in-gradle-7-0/34061

**Comment by SirSoundfont** [comment]
I saw that during my googling endeavors, but I can't figure out how to make a settings.gradle file, if that's even the reason I'm unable to run "gradle help". When you have time, please do retest it and update the instructions to work with the new versions of the technologies used, as well as any other necessary installations on a new M1 Mac without Xcode or any Java tools.

**Comment by R-A2433** [comment]
@spkane   Nice to meet to! I'm sorry to interrupt you. I'm trying to install Discord-Audio-Stream-Bot. Like SirSoundfont, I always get an error when I run "gradle build". Whenever I run gradle build in the terminal, I get the following error message:


FAILURE: Build failed with an exception.

* Where:
Build file '/Applications/Discord-Audio-Stream-Bot/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'Discord-Audio-Stream-Bot'.
> Could not find method compile() for arguments [net.dv8tion:JDA:4.2.1_262] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


So, could you please fix the error?

**Comment by baseckas** [comment]
What gradle version should be used to build this? Cannot install using 7.xx which gives error as above. Using 6.9 gives other type of exception.

**Comment by BinkanSalaryman** [comment]
@baseckas I've built the project using gradle 5.2.1, integrated in Intellij IDEA

**Comment by bobeckert** [comment]
@BinkanSalaryman I've just put up [PR #52 ](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/pull/52) which fixes this on Mac, with Gradle 7.0 and 7.1.1.   

@baseckas, @R-A2433  [This branch](https://github.com/bobeckert/Discord-Audio-Stream-Bot/tree/gradle-7.1.1) may help.
