### ISSUE TITLE
fatal error windows

### ISSUE THREAD

**Issue by xiopipe** [BinkanSalaryman/Discord-Audio-Stream-Bot#44]
hi, I'm trying to run this program but i can't.
I have this error
![image](https://user-images.githubusercontent.com/51303452/120081896-80dbbd80-c085-11eb-8a94-6e7c0f876e3b.png)

with both win32 and win64.
this is the app.log.
[app.log](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/files/6565210/app.log)
I hope that anyone can help me
I have java 8 Update 291

**Comment by BinkanSalaryman** [comment]
Uhm, did you compile from source code using java 9? Because the log is quite suspicious...

**Comment by xiopipe** [comment]
> Uhm, did you compile from source code using java 9? Because the log is quite suspicious...

eeem i'm using java 8. should i use java 9??

**Comment by xiopipe** [comment]
jejeje... i uninstalled Java SE Development Kit 16.
that was the error.
I will close this comment thanks
