### ISSUE TITLE
Support stage channels

### ISSUE THREAD

**Issue by MAXOUXAX** [BinkanSalaryman/Discord-Audio-Stream-Bot#47]
It would be great if the bot could join stage channels.
Currently, if you try to make the bot join a stage channel using its id, it'll throw this error: `Can't find specified voice channel!`

Supporting stage channels would be a great feature :)

**Comment by BinkanSalaryman** [comment]
I've looked into the topic and it'd make perfect sense to implement it. I'm afraid we'll have to [wait for JDA](https://github.com/DV8FromTheWorld/JDA/issues/1572) to support stage channels first, though.

**Comment by MAXOUXAX** [comment]
For sure!
I wasn't sure if JDA supported them yet and I wasn't even aware that stage channels launched without any API.
I'm not even sure they will add API endpoints to use them since apart from playing music to a large group of people, there's very few use cases.
And I'm also not sure it would technically be legal to play copyrighted content to that big of an audience.

Let's wait and see :/
