### ISSUE TITLE
Can't find either run win64.bat or run win32.bat

### ISSUE THREAD

**Issue by h6havok** [BinkanSalaryman/Discord-Audio-Stream-Bot#51]
I've installed a JRE and updated my environment path, but I can't find any .bat file in the code. How do I launch the program?

**Comment by BinkanSalaryman** [comment]
In the downloads section in the README.md, there's a zip with the compiled (runnable) jar file and the launch scripts. Unless you want to check something or built it yourself there should be no need to donwload the code.
