### ISSUE TITLE
Why Use Google Drive?

### ISSUE THREAD

**Issue by JBlocklove** [BinkanSalaryman/Discord-Audio-Stream-Bot#59]
Why are you sharing the build through Google Drive and not just setting up a release through Github? Google seems to think that zip has a virus and it makes it hard to download, and the releases feature of Github exists for this exact purpose...

**Comment by aksu560** [comment]
Wondering the same thing, currently facing issues with downloading from Drive.

**Comment by BinkanSalaryman** [comment]
Why, because Git it a hassle to me and I cannot be bothered to tag every commit which isn't cosmetic.
*sigh* Well I guess I have to give it another try...

**Comment by aksu560** [comment]
Issue with google drive is that it has apparently warned about potential malware for a couple releases now, and makes it difficult to download a build.

**Comment by Mazdad** [comment]
I just copied it in the Google Drive after trying to download it. I was able to download the copy of the file (it made me the owner of the copy) and bypass the whole virus scanning issue.
