### ISSUE TITLE
everytime i do a command it says i can not do that

### ISSUE THREAD

**Issue by PlushBanshee** [BinkanSalaryman/Discord-Audio-Stream-Bot#6]
also what am i so pose to put here and what symbles are use since you blured out the hole text i know your trying to keep privacy but you could of made the text like "xxxxxxxxxxx" or something becouse when i put my id in and boot the bot it gives me a red error becouse i used the wrong code style (also my discord wasn't showing your name sorry for thinking you blocked me 👍 )
![image](https://user-images.githubusercontent.com/31914937/45748153-44583280-bc4b-11e8-8367-0daf202b47c9.png)

**Comment by PlushBanshee** [comment]
never mind the owner help me on discord and that i'm therey thankful for keep up the great work now i can steam my .mid/.midi music to my frainds since there is no discord bot out there that can do it right this works great with virtual midi synth with the vb cable output setting

**Comment by BinkanSalaryman** [comment]
(New build has fixed permission system).
Read "permissions syntax" 🙂
