### ISSUE TITLE
Timeouts after joining channel

### ISSUE THREAD

**Issue by Azahliil** [BinkanSalaryman/Discord-Audio-Stream-Bot#68]
I've been using the Discord-Audio-Stream-Bot for our Remote-TableTopRPG nights as a little bit a of a music and sound bot, and everything has been working fine until just now when I tried to start the bot, get him in a channel and play some music through it.

In the UI everything seems fine at first, until the ping seemingly randomly jumps to over 6 seconds and the bot disconnects from the channel before immediately reconnecting and repeating the loop. For the brief moments when the bot is seemingly connected there is also no audio playing from the bot as far as I can tell.

I really have no clue whatsoever why this is happening all of a sudden, but I hope someone can help me fix it :(

I atteched the app.log in hopes it may contain some useful information 
[app.log](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/files/10863790/app.log)

**Comment by Azahliil** [comment]
I just tried it again this morning, and apparently everything seems to be working fine again, so I assume it was discord side problem that they've fixed?

**Comment by amarhany20** [comment]
same issue for me now

**Comment by ODENYGG** [comment]
Same

**Comment by KitBallard64** [comment]
Yeah. I can also attest to this lil guy having a connection issue.

**Comment by bobeckert** [comment]
Similarly confirmed. I am experiencing the same issue.

I wish I had older log files to compare to. I am seeing CFRayID and I do not remember seeing this previously. This is making me wonder if Discord has recently changed to start using Cloudflare?

**Comment by KitBallard64** [comment]
> Similarly confirmed. I am experiencing the same issue.
> 
> I wish I had older log files to compare to. I am seeing CFRayID and I do not remember seeing this previously. This is making me wonder if Discord has recently changed to start using Cloudflare?

Not sure. I think this goes in hand with the thread I linked, as that thread started the same time frame as this one's OP did. And said it went away after a bit for them. So I'm personally leaning towards that thread as a possible avenue to look into.

**Comment by pgDora56** [comment]
Same.
I don't know much about this program, but I think it has to do with time. 

Here are the results of my trial (All time are GMT):
- 5 p.m. on 20th: not available
- 5 a.m. on 21st: worked fine
- 1 p.m. on 21st: not available

In my case, when not available, it remained not available for a while.

**Comment by amarhany20** [comment]
well yeah I tested more than one pc, more than one discord bot, more than one server. same 6000ms. and if you have the same problem then, there is something that discord did that affected the bot.

**Comment by Atis9** [comment]
I made the following modifications and built it and it worked.

```diff
diff --git a/build.gradle b/build.gradle
index fd664f5..17c1a67 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,7 +1,7 @@
 plugins {
     id 'java'
     id 'application'
-    id "com.github.johnrengelman.shadow" version "5.2.0"
+    id "com.github.johnrengelman.shadow" version "8.1.1"
 }
 
 group 'net.runee'
@@ -20,7 +20,7 @@ repositories {
 }
 
 dependencies {
-    implementation "net.dv8tion:JDA:4.3.0_291"
+    implementation "net.dv8tion:JDA:4.4.1_353"
 //    implementation "com.sedmelluq:lavaplayer:1.3.42"
     implementation "com.jgoodies:jgoodies-forms:1.9.0"
     implementation "com.jgoodies:jgoodies-common:1.8.1"
```

**Comment by KitBallard64** [comment]
> I made a Docker-enabled patch to make building easier, so please feel free to use it.
> 
> [Discord-Audio-Stream-Bot.patch](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/files/11044344/Discord-Audio-Stream-Bot.patch)

Nice but uh... I don't get it.

**Comment by Sylvache** [comment]
> > I made a Docker-enabled patch to make building easier, so please feel free to use it.
> > [Discord-Audio-Stream-Bot.patch](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/files/11044344/Discord-Audio-Stream-Bot.patch)
> 
> Nice but uh... I don't get it.

Same :/

**Comment by BinkanSalaryman** [comment]
Big thanks to @Atis9, currently working on updating the libraries / integrating the patch. Works great so far, just trying to get a few minor things done before I push the changes and release a new version.

**Comment by BinkanSalaryman** [comment]
The new release should have fixed the issue.

**Comment by BillyNat** [comment]
Hey, thank you for updating the bot!

Unfortunately, I can't open the bat file. When I try to execute it, I get 
"Error: Could not create the Java Virtual Machine
Error: A fatal exception has occurred. Program will exit."
And if I try with executing it as an Admin, I get: 
"Error: Unable to access jarfile Discord Audio Stream Bot.jar"

I'm sorry, I'm such a nooby as far as this is all concerned, can anyone help?

**Comment by Sylvache** [comment]
> The new release should have fixed the issue.

Would it be possible to have a new download link plz ? The latest available is: Latest build (2021-07-03)

**Comment by BinkanSalaryman** [comment]
> Hey, thank you for updating the bot!
> 
> Unfortunately, I can't open the bat file. When I try to execute it, I get "Error: Could not create the Java Virtual Machine Error: A fatal exception has occurred. Program will exit." And if I try with executing it as an Admin, I get: "Error: Unable to access jarfile Discord Audio Stream Bot.jar"
> 
> I'm sorry, I'm such a nooby as far as this is all concerned, can anyone help?

Try updating your java to at least jre8, see #67

**Comment by Sylvache** [comment]
> > Would it be possible to have a new download link plz ? The latest available is: Latest build (2021-07-03)
> 
> Can't confirm:
> 
> ![image](https://user-images.githubusercontent.com/6740731/227329623-b6151883-f22c-4969-9f24-8e217c3a59f5.png)

Arf i'm stupid :/ 
Thanks haha

**Comment by Wraithage** [comment]
> Try updating your java to at least jre8, see #67

Thanks for staying with us on this. I updated to Java current release, 8u361, and also unblocked the .jar file. Unfortunately, I'm still seeing the same errors as BillyNat.
<img width="472" alt="java" src="https://user-images.githubusercontent.com/128744181/227337261-7dcd01c4-234a-4143-9e37-8016a034d8c2.png">
<img width="269" alt="security" src="https://user-images.githubusercontent.com/128744181/227337558-84755b4a-e44c-425a-b477-fb90e1dcc05e.png">
![image](https://user-images.githubusercontent.com/128744181/227338363-22e9ba3e-73f0-4c12-b2d3-38de5d7f74e6.png)

**Comment by BillyNat** [comment]
I've tried updating Java to 8, didn't work. Then I installed the Java SE dev kit 17, then it worked!

Thanks!

**Comment by BinkanSalaryman** [comment]
> I updated to Java current release, 8u361, and also unblocked the .jar file. Unfortunately, I'm still seeing the same errors
Well, I'm sorry but I still have no clue why it sometimes does this. But the errors are related to java in general and not this software in particular. There are plenty articles on the web about those, and hopefully, if you dig enough, you will find a way that works for you.

**Comment by Wraithage** [comment]
> > I updated to Java current release, 8u361, and also unblocked the .jar file. Unfortunately, I'm still seeing the same errors
> 
> Well, I'm sorry but I still have no clue why it sometimes does this. But the errors are related to java in general and not this software in particular. There are plenty articles on the web about those, and hopefully, if you dig enough, you will find a way that works for you.
> 
> May be it _doesn't_ work for java version 8 **because** I added the line "--add-exports" thing for java v9+ modules quite a while back.

Not to worry, I'm just reporting. Again, we all appreciate you looking at it.

But I can confirm what BillyNat said above, *except* that I installed JDK 20 instead of 17. It's working once that's in. So there's obviously some difference between the java executables in the JRE and the JDK. 

Thanks again!

**Comment by BinkanSalaryman** [comment]
@Sylvache I realized it's partially my fault for not updating the README.md file, while updating it because I saw it was quite dated already. Sorry for that!

**Comment by KitBallard64** [comment]
Just wanted to confirm that it looks like the issue is solved on my side. Thank you again~♥
