### ISSUE TITLE
Fatal error on startup

### ISSUE THREAD

**Issue by nahupyrope** [BinkanSalaryman/Discord-Audio-Stream-Bot#73]
I saw you posted a new release with a fix for the issue I was having with your previous one and made a single .bat file, but this one is also giving me another issue where it crashes on startup, I'll attach the app.log
[app.log](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/files/11069877/app.log)

**Comment by nahupyrope** [comment]
Fixed it by installing https://www.oracle.com/my/java/technologies/downloads/#jdk17-windows

Should've checked on closed tickets before posting, my bad!

**Comment by BinkanSalaryman** [comment]
Uhm, that's weird... Is it really happening on today's release?

**Comment by nahupyrope** [comment]
Yes!, older releases worked just fine, but installing jkd17 fixed it!

**Comment by BinkanSalaryman** [comment]
In theory, it should just work fine on java 8 or above, but apparently still not quite. Could you run the .bat file from cmd.exe and paste what it shows? I expect it to issue "start javaw -Djava.library.path="natives/win32/" -jar "Discord Audio Stream Bot.jar"....

**Comment by nahupyrope** [comment]
It issued: 

start javaw -Djava.library.path="natives/win64/" --add-exports="java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED" -jar "Discord Audio Stream Bot.jar"

**Comment by BinkanSalaryman** [comment]
Still
16:12:07 [main] INFO  net.runee.misc.Utils - OS architecture : x86       
16:12:07 [main] INFO  net.runee.misc.Utils - Java version    : 1.8.0_361 

> It issued:
> 
> start javaw -Djava.library.path="natives/win64/" --add-exports="java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED" -jar "Discord Audio Stream Bot.jar"

app.log/java said os architecture is x86 - implying 32 bit architecture, but batch file said %programfiles(x86)% variable **doesn't** exist - implying 64 bit architecture. Maybe you have an idea what's wrong there?

**Comment by BinkanSalaryman** [comment]
Sorry, I'm confused, updated my comment.

**Comment by nahupyrope** [comment]
I have no idea what could be the issue, OS is 64 bit

**Comment by BinkanSalaryman** [comment]
Maybe the issue is that you had a java 1.8.0_361 for Windows x86 (= 32 bit arch)  installed?

**Comment by nahupyrope** [comment]
That could actually be, let me check

**Comment by nahupyrope** [comment]
I have no way of telling which version of Java I installed, but I'm assuming I did have x86 installed instead of x64

**Comment by BinkanSalaryman** [comment]
Just did a quick test, and in fact it does yield this error. On the flip side, if does boot up successful if I change the bat to use the 32 bit natives instead...

**Comment by nahupyrope** [comment]
Good to know!, I updated to x64.
