### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by Airostat** [BinkanSalaryman/Discord-Audio-Stream-Bot#77]
can't make work new version.
can make work old one with jdk17

delited all java and install last jre 64 
![1](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/assets/138267840/2151afe6-61ae-4f5d-a77e-efc8f37d4266)
did make sure path is set
![2](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/assets/138267840/d24ce8ec-5724-4b15-a466-3f6e9e3fa1be)
still have the error

what am i doing wrong?
 if i start "run win" it do nothing
 if i start "run win" as administrator this error pop up 
![4](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/assets/138267840/e6824955-d322-4443-8aa4-b203daaeb44d)
 if i start "Discord Audio Stream Bot" app log is made
[app.log](https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/files/11923967/app.log)

**Comment by Airostat** [comment]
Solved!
path to the bat must NOT inclune spaces
can you rename "Discord Audio Stream Bot" without spaces so dumb people like me can just click on "run win" after extraction from zip?

**Comment by BinkanSalaryman** [comment]
> path to the .bat must NOT inclune spaces
> just click on "run win" after extraction
Why does the path the the batch file containing spaces matter on your machine? Usually you can surround a path with "" to make it recognize the whole thing as a path rather than individual arguments split by whitespace characters...

**Comment by Airostat** [comment]
> > path to the .bat must NOT inclune spaces
> > just click on "run win" after extraction
> 
> Why does the path to the batch file even matter on your machine? Usually you can surround a path with "" to make it recognize the whole thing as a path rather than individual arguments split by whitespace characters...

dont know why) i rename the folder and it suddenly worked
tried this https://github.com/BinkanSalaryman/Discord-Audio-Stream-Bot/issues/73#issuecomment-1483914257 and realise that i can not use spase in cmd. tried to rename folder and bot was working fine)
