### ISSUE TITLE
Audio stream stops when I disconnect from rdp

### ISSUE THREAD

**Issue by BurmazDaniel** [BinkanSalaryman/Discord-Audio-Stream-Bot#79]
Hey!
I am straming audio to discord from motherboard line in using your app. It is running on a computer that dose not have a gpu and i can acces it only thru rdp. 
Every time when I turn on the bot and quit rdp the audio stops playing. I have to rejoin the bot on my discord channel with `/leave` and `/join`.
It is not a huge problem but do you think there is any way to solve this problem?
Thank you!

**Comment by BinkanSalaryman** [comment]
Interesting. Does the log say anything at the time when you quit rpd?

**Comment by BurmazDaniel** [comment]
> Interesting. Does the log say anything at the time when you quit rpd?

Unfortunately there is no log after i quit rdp. I just get these after rejoin:
```
DEBUG n.d.j.internal.audio.AudioWebSocket - Using encryption mode xsalsa20_poly1305_lite
DEBUG n.d.j.internal.audio.AudioWebSocket - Unknown Audio OP code.
DEBUG n.d.j.internal.audio.AudioWebSocket - Audio connection has finished connecting!
```

**Comment by BinkanSalaryman** [comment]
I have no idea why it does that then :/

**Comment by arctickitty** [comment]
this is a microsoft but they refuse to fix rdp causes the audio endpoint to reset to compensate for this in the software all you have to do is regrab the audio device when its lost normaly muting and unmuting fixes this but ofc it will never recover if they program doesnt try to get the device back

**Comment by BurmazDaniel** [comment]
> this is a microsoft bug they refuse to fix rdp causes the audio endpoint to reset to compensate for this in the software all you have to do is regrab the audio device when its lost normaly muting and unmuting fixes this but ofc it will never recover if they program doesnt try to get the device back

Oh. Thanks for this info. I am closing this as this is more of a RDP issue.

**Comment by arctickitty** [comment]
you know the dev could have fixed this by just retrying the device once its lost because it will come back once rdp closes the program just never trys to get it back
