### ISSUE TITLE
Is there a way to add channel ID to config.json for auto-connect on the bot launch?

### ISSUE THREAD

**Issue by SystemChanger** [BinkanSalaryman/Discord-Audio-Stream-Bot#8]
Hi there! I am new to C# and don't understand the half of the code but your bot is amazing and does the same that i need.
How can i add voice channel ID to auto-connect and start playing the music when the bot launches?
Thank you for your job!

**Comment by BinkanSalaryman** [comment]
Unfortunately, there is no option to do this currently.

**Comment by BinkanSalaryman** [comment]
New version includes auto-join voice option in config.json:

```
{
  ...
  "voice": {
    ...
    "autoJoinVoiceChannels": {
        "<guild-id>": "<channel-id>",
        "<guild-id>": "<channel-id>",
        "<guild-id>": "<channel-id>"
    }
  },
  ...
}
```

You have to manually fill in the guild-channel id pairs in there before restarting. I might add a no discord/text command in the future for that.
