### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cajunlee** [BinkanSalaryman/Discord-Audio-Stream-Bot#9]
Hello, first off I want to say this is excatly what I've been looking for, but I do have a question.. would it be possible to make the bot respond to PTT (Push To Talk)? Instead of constant streaming voice?

**Comment by BinkanSalaryman** [comment]
Yes and no. This project's goal is to provide a low-level interface between discord voice api and audio device windows api... As of now, only sending "speaking" audio to discord is proven to work reliably. Now, if you would like to let the bot user respond to spoken commands, you could either rewrite the project to your needs, or write a wrapper on the audio devices, most likely in conjunction with VAC. This would require receiving "listening" audio  from discord to work reliably. And I'm not sure if you want to bind to specific users, not the mixed output.

**Comment by BinkanSalaryman** [comment]
If you are experience in coding we could collaborate on that, but I'm probably not much of a help when it comes to voice recognition - which is what you are asking for.

**Comment by cajunlee** [comment]
Ya I wouldn't mind, I've mainly done Web Development, and I've been making some headway on what I'm aiming for.. but I'm coming across the issue you stated above about it being reliable. If I get something together I'll def let you know, I haven't messed much with the discord api but I've scanned over it.. I'm seeing what I can do till they decide to make a Voice Commander option such as TS3
